# Site settings
title: Andrew Joshua Flores Díaz
description: Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Andrew Joshua Flores Díaz
user_description: Egresado de Ciencia de Datos y Aprendizaje Automático, actualmente estudiante de Ingeniería Industrial. 
  Soy de Perú, con dominio de inglés (C1) e italiano básico. 
  Cuento con más de 2 años de experiencia en proyectos personales dentro del campo de la ciencia de datos y el aprendizaje automático. 
  Mi objetivo es seguir creciendo en el mundo de la Inteligencia Artificial, ampliando conocimientos y aportando soluciones innovadoras.
user_title: Data scientist
email: joshuaxarg@gmail.com
# twitter_username: lorem_ipsum
instagram_username: andrewjoshuaflores
linkedin_username: in/joshua-flores-díaz-09630134b/
github_username:  JoshuaDs69
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

